In [1]:
import numpy as np
import pandas as pd
import os, time
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau

In [2]:
height = 180
weight = 85
sex = 1
age = 20
bmi = weight*10000 /height**2 
ability = 4
height = (height-170)/30
weight = (weight-70)/30
age = (age-30)/30
bmi = (bmi-30)/20
input_data = [[height, weight, sex, age, bmi, ability]]
input_data

[[0.3333333333333333, 0.5, 1, -0.3333333333333333, -0.1882716049382717, 4]]

In [3]:
dataset_dir = 'C://project//dataset/kwix/curation'
user_data = pd.read_csv(dataset_dir + '/user.csv')
user_data = user_data.to_numpy()
user_data[:,1] = (user_data[:,1]-170)/30
user_data[:,2] = (user_data[:,2]-70)/30
user_data[:,4] = (user_data[:,4]-30)/30
user_data[:,5] = (user_data[:,5]-30)/20
user_similarity = np.corrcoef(input_data,user_data[:,1:])[0,1:]
user_similarity

array([0.99044981, 0.97900025, 0.94566097, 0.9525501 , 0.99836038,
       0.94555515, 0.98260152, 0.90964213, 0.9587514 , 0.9206933 ,
       0.76709485, 0.78646674, 0.99350682, 0.99967703, 0.96261132,
       0.88791451, 0.73159055, 0.88430451, 0.88998961, 0.99787225,
       0.88677345, 0.93531926, 0.92136435, 0.93277536, 0.94418774,
       0.96990295, 0.98459142, 0.9933784 , 0.94018077, 0.915149  ,
       0.9508887 , 0.99806092, 0.92978844, 0.81878178, 0.9263759 ,
       0.94294273, 0.94126573, 0.77793787, 0.89101891, 0.85157894,
       0.84820037, 0.98039926, 0.90088097, 0.98143797, 0.78765824,
       0.88661185, 0.9076279 , 0.98050843, 0.99431479, 0.75089371,
       0.99453545, 0.94716117, 0.94214837, 0.9531711 , 0.84235374,
       0.22706205, 0.75388281, 0.83803993, 0.95423292, 0.98517783,
       0.93171527, 0.88196613, 0.36664032, 0.99959343, 0.95617187,
       0.70595459, 0.96649542, 0.97383008, 0.88336707, 0.86646203,
       0.40544422, 0.76679914, 0.99087761, 0.95838797, 0.92840

In [4]:
chest_df = pd.read_csv(dataset_dir +'/chest.csv')
chest = pd.read_csv(dataset_dir +'/chest.csv').to_numpy()[:, 1:]
lower = pd.read_csv(dataset_dir + '/lower_body.csv').to_numpy()[:, 1:]
abdom = pd.read_csv(dataset_dir + '/abdominals.csv').to_numpy()[:, 1:]


In [5]:
mean_probability = np.dot(user_similarity, chest) / user_similarity.sum()
mean_probability

array([0.00665107, 0.00769876, 0.00723921, 0.18481129, 0.22631486,
       0.23819849, 0.22789556, 0.16743819, 0.15044128, 0.15088905,
       0.15983932, 0.16337196, 0.15727566, 0.15193529, 1.        ])

In [6]:
x = (mean_probability.argsort())[::-1]
print(x)

[14  5  6  4  3  7 11 10 12 13  9  8  1  2  0]


In [7]:
chest_df.columns[x[0:5] + 1]

Index(['벤트오버덤벨레이즈', '인클라인푸쉬업', '바이셉스푸쉬업', '디클라인푸쉬업', '업앤다운푸쉬업'], dtype='object')