In [30]:
import numpy as np
import pandas as pd
import os, time
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau

In [31]:
height = 180
weight = 85
sex = 1
age = 20
bmi = weight*10000 /height**2 
ability = 4
height = (height-170)/30
weight = (weight-70)/30
age = (age-30)/30
bmi = (bmi-30)/20
input_data = [[height, weight, sex, age, bmi, ability]]
input_data

[[0.3333333333333333, 0.5, 1, -0.3333333333333333, -0.1882716049382717, 4]]

In [32]:
dataset_dir = 'C://project//dataset/kwix/curation'
user_data = pd.read_csv(dataset_dir + '/user.csv')
user_data = user_data.to_numpy()
user_data[:,1] = (user_data[:,1]-170)/30
user_data[:,2] = (user_data[:,2]-70)/30
user_data[:,4] = (user_data[:,4]-30)/30
user_data[:,5] = (user_data[:,5]-30)/20
user_similarity = cosine_similarity(input_data,user_data[:,1:])
user_similarity

array([[0.98162399, 0.97981126, 0.78708098, 0.79814314, 0.99839197,
        0.90551717, 0.97715902, 0.93333754, 0.94967787, 0.8719778 ,
        0.70541189, 0.81524786, 0.99471176, 0.99958326, 0.93820786,
        0.90996954, 0.77959108, 0.73890123, 0.91889594, 0.99824175,
        0.85873122, 0.94923897, 0.94283028, 0.75398139, 0.91519455,
        0.8694088 , 0.98471084, 0.98467713, 0.92786531, 0.90981909,
        0.94582978, 0.99857508, 0.85233272, 0.8270911 , 0.94220217,
        0.90257699, 0.75007381, 0.75349368, 0.91803049, 0.88754578,
        0.86004619, 0.98386338, 0.9276179 , 0.92754795, 0.84917501,
        0.91762678, 0.9295411 , 0.98380006, 0.99530575, 0.82470176,
        0.99246088, 0.85525807, 0.94283121, 0.94706898, 0.87994557,
        0.43248303, 0.82699477, 0.87404518, 0.95642485, 0.98251427,
        0.94978929, 0.88207278, 0.48011267, 0.99959405, 0.86914479,
        0.69484044, 0.97383943, 0.95826426, 0.91572954, 0.90364399,
        0.44087253, 0.76595126, 0.98673258, 0.95

In [33]:
chest_df = pd.read_csv(dataset_dir +'/chest.csv')
chest = pd.read_csv(dataset_dir +'/chest.csv').to_numpy()[:, 1:]
lower = pd.read_csv(dataset_dir + '/lower_body.csv').to_numpy()[:, 1:]
abdom = pd.read_csv(dataset_dir + '/abdominals.csv').to_numpy()[:, 1:]


In [34]:
mean_probability = np.dot(user_similarity, chest) / user_similarity.sum()
mean_probability

array([[0.01038886, 0.01237165, 0.01108219, 0.18068043, 0.22278363,
        0.23393651, 0.22595008, 0.16887588, 0.15125464, 0.15325808,
        0.16172969, 0.16164781, 0.15574387, 0.1502967 , 1.        ]])

In [35]:
x = (mean_probability.argsort())[0][::-1]
print(x)

[14  5  6  4  3  7 10 11 12  9  8 13  1  2  0]


In [36]:
chest_df.columns[x[0:5] + 1]

Index(['벤트오버덤벨레이즈', '인클라인푸쉬업', '바이셉스푸쉬업', '디클라인푸쉬업', '업앤다운푸쉬업'], dtype='object')